ccmlib/cmds/node_cmds.py, ccmlib/node.py
This PR contains some improvements for the sstablesplit command:
* Add --no-snapshot option
* Add the capability to specify what file(s) to split. This was broken before and it was splitting all sstables everytime. I fixed this so we can now specify 1 or more files to split.
* This doesn't affect sstable2json, this command doesn't accept sstable file(s) in parameter.
* The only thing that could affect dtests would have been the parameter name change (datafile -> datafiles). I verified and it is not used at all in dtest.
=> Add --no-snapshot option to sstablesplit and improve the support to specify files

ccmlib/node.py
Useful if we expect a stress command to fail, and want to ignore the 1000+ lines of errors.
=> stress command: Forward extra kwargs to subprocess.call

ccmlib/cluster.py
Bumps DC token offsets from 1 to 100, this allows for better support of bootstrapping a node without an initial_token and for replacing a dead node.
I encountered an issue while creating a cluster with 2 datacenters with 2 nodes in each and then bootstrapping a new node in the 2nd datacenter:
ccm create test12192 -n 2:2 -s -v 1.2.19
ccm add node5 -i 127.0.0.5 -j 7500 -b -d dc2
ccm node5 start --wait-other-notice --wait-for-binary-proto
This will fail inconsistently depending on what node is chosen to generate the token to bootstrap the node with.   node5 will fail to bootstrap if it tries to acquire a token from node3 since node3 takes the midpoint of it's range (`-9223372036854775807..-9223372036854775808`) which returns the token for node0 (`-9223372036854775808`) given the ring …
=> Use a larger offset for multi-DC tokens.

ccmlib/cmds/cluster_cmds.py, ccmlib/node.py
I had trouble to execute all tools except run_sstable2json(). So I moved the permission checking code from there into a new method find_cmd() which is called by all other run* methods for retrieving the path to the command with fixed permissions. 
**Edit:** PR has been rebased onto develop as requested. Please be aware that I haven't tested this against develop yet (will do next week).
=> Fix invalid file permissions for running sstable related commands

README.md
I've repeated the section about aliases on MacOS directly after the ccm start command.
I know it's already specified in the requirements, but it's easy to miss it and just go directly to the configuration steps.
I've wasted 15 minutes trying to figure out why I get the "[Errno 48] address already in use" message all the time ;)
=> Info about MacOS aliases repeated in the configuration steps.

ccmlib/node.py
__gather_sstables would return no results for pre 2.1 as cf data directories don't have suffixes.
=> fixed gather_sstables cf directory matching for <2.1

ccmlib/node.py
Cassandra 1.1 will fail to start due to invalid num_tokens config value without patch.
=> fixed invalid num_tokens config value for pre-1.2

.gitignore, setup.py
This will make a copy of the ccm script and give it a py extension if Windows installation detected.
=> Add py Extension During Windows Installation

ccmlib/node.py, tests/test_lib.py
as discussed in #245.
Presumably we should remove the deprecation warning at some point. Shall we start a major-version milestone list or something?
=> uses `nodetool info` to get node's data size

ccmlib/cmds/cluster_cmds.py
* Adds proper exit codes
* Adds warning when user tries to start unpopulated cluster
This is a nit, but one that keeps biting me.
=> Cleans up CLI start command

ccmlib/node.py
Fixes #248.
This change relies on the major assumption that we never call `watch_log_for` on a node whose pid we do not know. It also hopes the user has the optional `psutil` dependency installed. `psutil` is optional because it is only required for Windows, and installation via `pip` is problematic, so users must install via the .msi on PyPI. This will make log parsing noticeably slower if `psutil` is not installed.
This PR hopes to solve the issue where with C* 2.1+ on Windows, when not running with legacy startup, the batch script that starts C* returns with exit code zero as soon as the Cassandra Daemon has started up. Thus, the log parsing will exit early, unless the sought after log line is found in the small window where the batch file is still alive.
I have noticed no change in …
=> Don't ever poll process on windows 

ccmlib/cmds/node_cmds.py
By typing the command below, we can see that the keyspace argument is not taken into account (there is a Note on the beginning of the output of the command):
ccm node1 ring myKS
This pull request allows to pass the options of nodetool commands
=> Fix nodetool options which are not passed

ccmlib/node.py
This doesn't change any behavior, it just fixes all of the complaints from pyflakes in node.py.  (This is useful, because pyflakes often catches coding errors, but they're hidden in the noise with all the PEP-8 warnings.  Plus, this makes the code cleaner :)
=> Fix PEP-8 and linter warnings

README.md
Currently README doesn't mention anything Binary distributions, one can find this information only in code.
=> Add a section on Binary distributions to README

ccmlib/node.py
suspend()
Suspend process execution with SIGSTOP signal pre-emptively checking whether PID has been reused. On UNIX this is the same as os.kill(pid, signal.SIGSTOP). On Windows this is done by suspending all process threads execution.
resume()
Resume process execution with SIGCONT signal pre-emptively checking whether PID has been reused. On UNIX this is the same as os.kill(pid, signal.SIGCONT). On Windows this is done by resuming all process threads execution.
=> Adding Windows support for pause/resume

ccmlib/node.py
I accidentally broke this in commit https://github.com/pcmanus/ccm/commit/10e8438c5c42d9fbbb3dcd168191a86f99fa9c70
=> Return stdout, stderr from nodetool

ccmlib/node.py, tests/test_lib.py
Several improvements here:
- The way `Node.run_cqlsh` split its input led to lots of lines that looked like `';\n'` getting sent to cqlsh, which leads to confusing syntax errors. This only sends `line + ';'` if `line.strip()` is non-empty.
- If the `show_output` kwarg to `run_cqlsh` is truthy, it prints all output. However, it skipped the first 4 lines. This may have been getting around some property of an old cqlsh, but this is no longer valid.
- Finally, this adds a `return_output` kwarg. If it's truthy, `run_cqlsh` will return cqlsh's output as a string.
Since `return_output` is a kwarg with a default value at the end of the argument list, this shouldn't change the `run_cqlsh` API; if you just ignore it, it won't affect you.
I've also tested the combination of these two kwargs and …
=> `run_cqlsh` improvements

ccmlib/node.py
Before, p.stderr was consumed printing each line, which meant that p.stderr.read() always returned an empty string. Now, stdout and stderr are flattened to strings before being processed and/or returned.
=> fixes stderr handling in run_cqlsh

ccmlib/node.py
The only thing I did to verify this change was to run the dtest mentioned [here](https://github.com/riptano/cassandra-dtest/pull/272) on 2.0, 2.1, and trunk:
```
set -x
for v in git:cassandra-2.0 git:cassandra-2.1 git:trunk ; do
CASSANDRA_VERSION=$v nosetests compaction_test.py:TestCompaction_with_DateTieredCompactionStrategy.dtcs_deletion_test
done
```
It fails on 2.0 without this change, and succeeds on all branches with it. So, the reviewer should keep in mind it's not tested very extensively.
=> fix data directory globbing in Node.get_sstable

ccmlib/node.py
This should fix the new dtest failures
=> Fix node.get_sstables() for Cassandra 2.2

ccmlib/node.py
The changes that I previously made on node.__update_envfile broke the function for Cassandra version less than 2.1 (where the ps0 file does not exist). This patch fix the problem.
=> Fix broken node.__update_envfile on windows for C* version less than 2.1

ccmlib/cluster.py
Also added 60 second timeout on watching startup instead of default 10 minutes
=> Revise default startup string watched for in cluster.start for 2.2+

ccmlib/node.py
This is an interim change to facilitate tracking down if specific dtests are consistently hanging. Windows only and just a little verbosity on node start.
=> Print pid of nodes when started on Windows

ccmlib/cluster.py
Normally when cluster.start() is called, none of the nodes are running,
so we wouldn't collect marks for any nodes, resulting in the later log
check doing nothing.  Instead, we can collect marks for any node and
then just make sure we don't watch a node's log for itself.
=> Improve behavior of wait_other_notice in cluster.start()

ccmlib/cluster.py, ccmlib/common.py, ccmlib/dse_node.py, ccmlib/node.py, ccmlib/repository.py
Created new helper method common.rmdir() to allow rmtree on path > 255 chars on Windows.
=> rmdir() to allow rmtree on path > 255 chars on Windows

README.md, ccmlib/repository.py
Allows for creation of clusters from github by specifying `github:username/branch_name` instead of `git:branch_name`, partially addressing #293.
This is pretty quick-and-dirty, but it seems to work. It creates a new `_git_cache` directory for each GitHub repo cloned, which could get big after a while.
This changes the existing format for cluster repo directories. Instead of replacing `:` with `_`, it replaces `:` with `COLON` and `/` with `SLASH`. Some replacement for the latter is necessary since `/` is valid in branch names, so we may encounter them in GitHub branches. Replacing them both with uppercase ascii gives each a unique replacement and makes it unlikely that directory names will collide. Users will want to run `ccm invalidatecache` after updating.
=> GitHub repos

ccmlib/node.py
I don't know if this goes against some design philosophy for `node.Node`, so I'm just running this up the flagpole. Seems like [this kind of logic](https://github.com/riptano/cassandra-dtest/pull/338/files#diff-abac0928e2a06eb362676fa694227510R122) could be repeated all over the place in dtests, so why not consolidate that all into one place?
=> add option to block on the log for Node.drain

ccmlib/cmds/cluster_cmds.py
`ccm list` lists valid clusters. `ccm cluster list` is not a valid command. Fixes #315.
=> Change suggested command on cluster op failure

ccmlib/common.py
This is just a little more compact and easy to read. Jankily tested from the interpreter:
```python
>>> from ccmlib import common
>>> import inspect
>>> inspect.getsourcelines(common.is_win)  # check that I'm using my new implementation
(['def is_win():\n', '    return sys.platform in ("cygwin", "win32")\n'], 215)
>>> # I totally am
...
>>> common.is_win()
False
>>> import sys ; sys.platform = 'cygwin'
>>> common.is_win()
True
```
=> makes is_win more readable and idiomatic

ccmlib/cmds/command.py, ccmlib/common.py, ccmlib/dse_node.py
The value of env var CCM_CONFIG_DIR is used as the config directory instead of ~/.ccm.  If CCM_CONFIG_DIR is not defined or empty, then ~/.ccm is used instead.
This change is useful for me (and hopefullly others) for 2 reasons.
1. My home dir was nearly full and I wanted to put CCM's state on a differencent partition and not have to specify --config-dir on every command.
2. Some data I deal with must be written on an ecrypted filesystem while others do not.
Symlinks/aliases/script/... can handle these issues.  The difference for me is, I set CCM_CONFIG_DIR to a relative path - therefore all my data, code, and ccm state is in one place.
One issue with these changes is the build repository is not shared.  I thought of adding an optional CCM_REPO_DIR env var for this.
I'm a relatively new …
=> Added use of the CCM_CONFIG_DIR environment variable

ccmlib/cmds/cluster_cmds.py, ccmlib/dse_node.py, ccmlib/node.py
Changes:
- Remove leftover references to dse_yaml_file option which is no longer supported
- Explain how to specify option.suboption with period separator
- Fix for delete conf setting by not providing the value (ex: "ccm updateconf key:")
I made the 3rd item a separate commit to make the fix more clear.
=> Improvements for updateconf, updatedseconf commands

ccmlib/node.py
there was an inversion on dry_run parameter (was being applied when dry_run=False)
=> fix node.run_sstableofflinerelevel 

ccmlib/cmds/cluster_cmds.py
This PR will add an option to run `setdir` for individual nodes (`*/node.conf`) instead of the whole cluster (`cluster.conf`). As briefly discussed in #341.
=> Allow setting directory for individual nodes

ccmlib/cmds/node_cmds.py
Currently `getsstables` prints the sstables formatted as a Python list of strings. This change prints them out without quotes, separated by newlines, so it's easier for unixy things to consume.
=> makes getsstables print files on separate lines

ccmlib/cluster.py, ccmlib/common.py, ccmlib/dse_node.py, ccmlib/node.py
I was encountering a very rare and small timing window when running tests on a constrained VM (2 cores, 4GB ram) that had ongoing load where the binary interface wasn't available after ccm start even if --wait-for-binary-proto was used.
Replacing `time.sleep(0.2)` with a method that verifies the binary interface is listening by attempting to create a socket to it seems to resolve my issue (so far).   Will try for up to 10 seconds (more than reasonable if 'Starting listening for CQL clients' is spotted in the logs) and prints a warning and continues on if the interface is still not available.
=> Establish socket to binary port for --wait-for-binary-proto to ensure port is listening.

ccmlib/cluster.py, ccmlib/node.py
Reference CASSANDRA-10075: The retry is an attempt to remedy an intermittent
failure in dtests where commitlogs cannot be deleted during cluster stop.
Flush before kill is an attempt to address a class of problems that has
shown up in various dtests while stabilizing Windows tests for 2.2.
=> Flush before kill on Windows. Add retry on deletion in cluster.remove()

ccmlib/cluster.py
The most important commits here are the first and second. It was not fun at all to figure out what the arguments to `create_node` were, so those commits switch to using kwargs. I also made the selection of which port number to use for debugging use a plain old `foo if debug else bar` instead of some wacky `(foo, bar)[debug == True]` stuff.
While I was in there, I fixed up a bunch of linter errors.
=> Cluster readability

ccmlib/node.py
Caused 11 new failures since flush failure can rebound w/raised exception. If we fail to flush on shutdown it's not really an error, so changed to swallow exception during stop() on Windows.
=> make flush failure silent on Windows node stop

ccmlib/cluster.py
This didn't account for the code path where node.nodelist() was
populated and class_names was None, or otherwise not iterable. If the
class_names parameter has its default value of None, this line will set
it to an empty (iterable) list.
=> fixes iteration over class names in set_log_level

ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/node.py
1. Stress tool options need to be _appended_ to argument list. Example for using stress tool directly:
`ccm stress user profile=...yaml 'ops(simple1=1)' -port jmx=7100`
1. jmx port will now be set automatically for node specific runs
=> Stress tool arguments not handled correctly

ccmlib/node.py
[PR363](https://github.com/pcmanus/ccm/pull/363) caused a [regression](http://cassci.datastax.com/view/cassandra-3.0/job/cassandra-3.0_dtest/lastCompletedBuild/testReport/sstablesplit_test/TestSSTableSplit/single_file_split_test/history/) on dtest `single_file_split_test` because that test specifies the `stdout` paramter on `kwargs`, what causes a conflict when calling `subprocess.Popen`, with `stdout=subprocess.PIPE`.
The fix is to provide and `output_file` parameter instead, similar to what is done in other tool methods, such as `run_sstablemetadata` or `run_sstableexpiredblockers`, so we can make a conditional on that before calling `subprocess.Popen`.
=> Removed kwargs from node.run_sstablesplit

ccmlib/node.py
* Change windows launch to use node cassandra.ps1.
* Remove VerifyPortsAreAvailable on Windows startup
* Fix a flake8 violation in node.py
=> Fix launch on Windows after CASSANDRA-9615

ccmlib/node.py
The `mark_log_for_errors()` creates a mark in the current position of the cassandra log of the given node, where all error logs before that mark will be ignored in the `grep_log_for_errors()` method.
The main use case for this right now, is to ignore all errors on cassandra 2.1 on Windows before upgrading to 2.2, in the context of `upgrade_internal_auth_test.py` (CASSANDRA-10037).
=> Added node.mark_log_for_errors() method

ccmlib/cmds/node_cmds.py
This gives a CLI command for getting the version of a node from its build.xml file. The name of the command isn't final; it looks kind of gross int the top-level usage statement:
```
$ ccm
Missing arguments
Usage:
ccm <cluster_cmd> [options]
ccm <node_name> <node_cmd> [options]
Where <cluster_cmd> is one of
create         Create a new cluster
add            Add a new node to the current cluster
[...]
or <node_name> is the name of a node of the current cluster and <node_cmd> is one of
[...]
pause          Send a SIGSTOP to this node
resume         Send a SIGCONT to this node
jconsole       Opens jconsole client and connect to running node
versionfrombuild Print the node's version as grepped from build.xml. Can be used when the node isn't running.
```
See that last line -- the command name …
=> add versionfrombuild command

ccmlib/common.py, ccmlib/dse_node.py
Added support for DSE 4.8.0.
* The dse jar filename changed from "dse-4.7.0.jar" to "dse-core-4.8.0.jar", modified get_dse_version to support new filename format.
* The dse 4.8.0 archive no longer contains ```resources/shark```, skip copying resources that don't exist.
=> Modifications for DSE 4.8.0 support

ccmlib/node.py
After CASSANDRA-10241, we have 2 log files by default.
Currently, ccm just replace contents of logback.xml to system.log, contents in system.log are now doubled.
This is causing dtest to fail when expecting only one log line is expected.
Proposed fix is to use `cassandra.logdir` env property.
Since that is available from 2.1, we can just remove replace code and add jvm option to it. (CASSANDRA-7136)
=> Use cassandra.logdir to specify log location

ccmlib/node.py
In CASSANDRA-10241, we introduced a separate debug.log. As part of this, a logger for org.apache.cassandra was added in addition to the root level. In order to preserve the existing set_log_level semantics in CCM, we need to also set the log level for this org.apache.cassandra logger.
=> Fix set_log_level after logging changes in CASSANDRA-10241

ccmlib/repository.py
Fixes bug where you couldn't check things out if the branch name was a valid SHA shortcut.
=> change git checkout command

ccmlib/node.py
Mainly this is to support debug.log introduced in CASSANDRA-10241.
This is necessary for some dtests (for example, CASSANDRA-10463).
=> Add support to watch any file under logs directory

ccmlib/repository.py
Reverts pcmanus/ccm#384
This breaks using git tags as versions, which is a way more common usecase than branches that also match sha's.
=> Revert "change git checkout command"

ccmlib/node.py
When using `JVM_EXTRA_OPTS` in command line and `jvm_args` in `node.start()`, those two are concatenated together without space.
For example, in [CASSANDRA-10452](https://issues.apache.org/jira/browse/CASSANDRA-10452), 
```
KEEP_LOGS=true JVM_EXTRA_OPTS=-da PRINT_DEBUG=true nosetests -xsv bootstrap_test.py:TestBootstrap.bootstrap_with_reset_bootstrap_state_test
```
will result in:
```
Unrecognized option: -da-Dcassandra.reset_bootstrap_progress=true
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
=> fix concat with jvm_args when starting up the node

ccmlib/cluster.py, ccmlib/cmds/cluster_cmds.py, ccmlib/common.py, ccmlib/repository.py
Added for #347.  Had to add to more places that seem right, but wanted to protect against: binary, src, git, github and install-dir options.
=> added check to validate jdk >= 1.8 when C* >= 3.0 and fail with useful message on startup

ccmlib/node.py
During rolling upgrades, the cluster version remains on the old
version as individual nodes are updated. When a node is upgraded
to 3.0+, this leads to the hints_directory setting not being added
to its config. In turn, this means that the hints dir defaults to
a location under CASSANDRA_HOME which is shared by all nodes in
he cluster. From that, all manner of hijinks ensue with nodes
wiping out each other's hints files, causing seemingly random
exceptions and other fun stuff.
=> Add hints_dir to conf based on node, not cluster version

ccm, ccmlib/cluster.py, ccmlib/cluster_factory.py, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/common.py, ccmlib/dse_node.py, ccmlib/node.py, ccmlib/repository.py, tests/ccmtest.py, tests/test_cmds.py, tests/test_common.py, tests/test_issues.py, tests/test_lib.py
I was taking a look at ccm's code with a checking tool I wrote (similar to pyflakes) that helped me prepare some PEP8, pylint and other fixes. If you guys think it's interesting, I could also send a PR to perform an automated CI job on each PR through Travis CI (this way, the amount of lint/pep8 errors that get into CCM master will reduce substantially).
=> PEP8 Fixes

ccmlib/common.py, ccmlib/node.py
Currently every call to `common.make_cassandra_env()` updates the node cassandra-env file with the current install dir and node conf dir. This method is used by many `node` commands, such as `nodetool`, `json2sstable`, `scrub`, `cqlsh`, etc to construct the environment variables, but it's not necessary to update the cassandra-env file every time these commands are called, only in the first time, or when the install dir changes.
This patch makes all node commands use `node.get_env()` instead of  `common.make_cassandra_env()`, and only updates the cassandra-env file in the first use, or when the install dir changes.
The motivation behind this is a race condition in the context of [CASSANDRA-10485](https://issues.apache.org/jira/browse/CASSANDRA-10485), where a nodetool command is called …
=> Only update node configuration when necessary

ccmlib/common.py
Fix for https://github.com/pcmanus/ccm/pull/376/files#diff-e19f0f0ec871623be418f8c4e97f9f46L530
The updated regex in that commit only supports DSE >= 4.8.0 (where the jar file name changed to dse-core-X.Y.Z.jar), and fails for earlier DSE versions (where the jar file name was dse-X.Y.Z.jar).
=> DSE Version Detection broken < DSE 4.8.0

ccmlib/node.py
I've chosen here to give the `jstack` method an optional `opts` parameter that takes a list of options, like you'd see in `subprocess.Popen`. The method returns directly the result of `subprocess.Popen()` so callers can do what they want with it, getting the output of `std{out,err}` or checking the return value.
The APIs for the `Node` methods that shell out to other processes are inconsistent (and some of them Are Bad), so I don't feel too bad about giving this an API that I like, but isn't consistent with the others. If you think I should feel bad, let me know.
I've smoke-tested this with this script:
https://gist.github.com/8e2552a5692730c65957
=> add jstack method to Node

ccmlib/cluster.py, ccmlib/dse_cluster.py, ccmlib/dse_node.py, ccmlib/node.py
Change jvm_args default value to None, then in the method
body check if it's None, then assign it to an empty list.
This avoids surprises if multiple calls to the methods
are made [1].
[1] http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments
=> ccmlib: Avoid passing mutable default argument to jvm_args

ccmlib/cmds/cluster_cmds.py, ccmlib/dse_cluster.py
This change would allow for users to provide a credentials file that contains dse_username and dse_password to use for credentials instead of passing them in explicitly.
I think this change would be useful for anyone who is trying to share common credentials, or keep credentials out of logs. 
The format of the credentials file would be as follows.
[dse_credentials]
dse_username = username
dse_password = password
=> Adding command line arg for credentials file.

ccmlib/cluster.py, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/dse_cluster.py, ccmlib/dse_node.py, ccmlib/node.py
CASSANDRA-8142 adds -R to allow bin/cassandra to run as root - this patch adds --root to the ccm node commands to add -R, allowing that same functionality. This allows scripts that run as root for whatever reason to continue working post-8142
=> Add flag to enable starting cassandra as root for CASSANDRA-8142

ccmlib/dse_node.py
The -Dcassandra.logdir= is set to  "/var/log/cassandra" by default 
This patch set the right path. 
It's work with the last dse (4.8.3)
=> Appears we cannot run DSE 4.7+ anymore #419

ccmlib/cmds/cluster_cmds.py, ccmlib/dse_cluster.py
I really like the recent addition of the '--dse-credentials' config parameter for loading credentials from a config file.   For convenience I think it would be nice if there were a default credentials file that, if exists, will be loaded to grab the dse credentials.   This would remove the need to pass the path of the credentials file each time you create a cluster.
The existing behavior:
* If user passes in --dse-credentials, grab dse_username and dse_password from the passed in config file.
* Else grab from --dse-username and/or --dse-password
The new behavior:
* If user doesn't pass in --dse-credentials and .dse.ini exists, set dse_username and dse_password based on it's contents.
* Else If user passes in --dse-credentials, grab dse_username and dse_password from the passed in config …
=> Use ~/.ccm/.dse.ini as dse credentials file if it exists by default.

ccmlib/dse_cluster.py, ccmlib/repository.py
It looks like I introduced an annoying regression in #426.   The log messages I added for informing a user that they were not providing DSE credentials were evaluated when running *any* command against a DSE cluster.   This should really only be logged before you go to download a DSE version.   This makes that adjustment so the log message only appears when it is relevant.   
Props to @kishkaru for noticing this :).
=> Only log dse credentials are missing when attempting to download.

ccmlib/node.py
As described in the [documentation] (https://docs.python.org/2.7/library/subprocess.html#subprocess.Popen.wait), using `p.wait()` may result in a deadlock. This seems to happen quite regularly on Windows, although I did see it once on Linux too. The solution is quite simple, just use `p.communicate()` instead. This should be safe provided the input and output can be buffered in memory.
=> Avoid potential deadlock when running cqlsh

ccmlib/node.py
We are missing the case where you want to replace a value
in cassandra.yaml that is normally a dict, with a single key.
For example, with just "None".
Fixes #434.
=> Only use dictionary update if the new value is a dictionary

ccmlib/dse_cluster.py
When attempting to create a DSE cluster using ccm, I get the following error: 
```
692    [main] DEBUG com.datastax.driver.core.CCMBridge  - Executing: ccm node1 start --wait-other-notice --wait-for-binary-proto --config-dir=/tmp/1452121136420-0
782    [Exec Stream Pumper] ERROR com.datastax.driver.core.CCMBridge  - ccmerr> Traceback (most recent call last):
782    [Exec Stream Pumper] ERROR com.datastax.driver.core.CCMBridge  - ccmerr>   File "/usr/local/bin/ccm", line 5, in <module>
782    [Exec Stream Pumper] ERROR com.datastax.driver.core.CCMBridge  - ccmerr>     pkg_resources.run_script('ccm==2.0.7', 'ccm')
782    [Exec Stream Pumper] ERROR com.datastax.driver.core.CCMBridge  - ccmerr>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
782    [Exec …
```
=> Fix byteman_port position in dse_cluster#create_node.

ccmlib/cluster.py, ccmlib/cmds/cluster_cmds.py
This adds a flag to change the authenticator to `PasswordAuthenticator` (with default credentials). It comes handy when doing unit testing of Cassandra drivers that need to test their implementation of the Plain text authenticator flow.
If #431 is accepted this could potentially be obsolete, though it can also be considered as syntactic sugar.
=> feature: add a flag to enable PasswordAuthenticator

ccmlib/cluster.py, ccmlib/node.py
@mambocab to review. The relevant test now passes locally for me. I'll try it out on cassci
=> Automatically set migration_task_wait_in_seconds to double node count

ccmlib/cluster.py, ccmlib/common.py
On Mac the user needs to make sure the loopback addresses (127.0.0.2, 127.0.0.3, etc.)
are created. Currently if they aren't created, ccm fails when creating the cluster,
but leaves it in a partial state (usually just the first node is running).
This change does a pre-flight check to make sure all loopbacks are available, print
a better warning, and exit before starting any nodes.
=> Improve handling when not all loopback addresses are available

ccmlib/cmds/node_cmds.py, ccmlib/node.py
W/ regards to wait-other-notice
@mambocab and @kishkaru to review. Running CI here: http://cassci.datastax.com/view/Dev/view/ptnapoleon/job/ptnapoleon-cassandra-2.2-dtest/
Should not affect DSE
=> Match the node start API to the cluster start API

ccmlib/cluster.py
This PR only checks interface availability for nodes that aren't started when doing a cluster.start(). This keeps the positive effects of the previous PR (no partial states if another cluster is left running or interfaces not available) while restoring idempotent starts and the ability to use start for only partially downed clusters.
=> Restore previous ability of cluster.start() to start partially downed clusters

ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py
* Node level command for `updatedseconf`  (i.e. `ccm node1 updatedseconf hive_metastore_enabled:false`)
* Add support for --yaml for node level commands.
* Small doc change for updatedseconf's yaml option.
=> Add node level command for updatedseconf. Literal yaml for node cmds.

ccmlib/cluster_factory.py, ccmlib/common.py, ccmlib/dse_node.py, ccmlib/node.py
This does a bunch of little things which may not be useful in the general case, but is good to have:
* Previously with updateconf/updatedseconf, someone could specify a nested structure, i.e.:
```bash
ccm updateconf "client_encryption_options.enabled: true"
```
This would update cassandra.yaml with:
```bash
client_encryption_options:
enabled: true
```
In the general case this is more than enough, but there were a few problems:
1. It would update in place for updateconf (i.e. if there are other options under client_encryption_options, those would remain unchanged), but not with updatedseconf (it'd blow away all children except the newly added element), reconciled that logic into `common#merge_configuration`.
2. You couldn't nest > 2 deep, i.e. …
=> Allow nesting > 2 for updateconf/updatedseconf, persist and read dse_config_options

ccmlib/node.py
This lets us get back strings instead of bytes in python3
@kishkaru to review
=> Set universal_newlines=True on subprocess.Popen. Closes #469

ccmlib/common.py, ccmlib/node.py
This allows me to spin up C* cluster newer the 3.2 with IPV6.
I tested these changes against 3.4, and 3.0.3  It seems wot work with both paths. 
Take a look and let me know. I'm not sure the "-Djava.net.preferIPv6Addresses=true" was needed as it worked fine without it so I left it absent, and simply removed '-Djava.net.preferIPv4Stack=true' from the jvm.options file
=> Fixing ipv6 for C* with versions > 3.2

ccmlib/node.py
Simple assertion that wait_other_notice and join_ring are not used together.
=> Assert that wait_other_notice and join_ring are not used together

ccmlib/node.py
=> Revert "Assert that wait_other_notice and join_ring are not used together"

ccmlib/node.py
[This code](https://github.com/beobal/cassandra-dtest/blob/10091/jmxutils.py#L55) from [@beobal's recent PR](https://github.com/riptano/cassandra-dtest/pull/887) is necessary but silly. This PR adds a method that makes it unnecessary.
(Also, if it weren't inconsistent with existing APIs, I'd make this a `@property`. Is that a refactoring we'd consider in the long term? If so, maybe we could make this one from the get-go.)
=> add node.Node.envfilename method

ccmlib/common.py, ccmlib/node.py
This makes the `wait_other_notice` and `wait_for_binary_proto` params able to specify timeouts if they are integers.
=> Timeout param node start

ccmlib/node.py, tests/test_lib.py
[CASSANDRA-9692](https://issues.apache.org/jira/browse/CASSANDRA-9692) unifies/improves logging/output of data sizes and rates throughout C*.
As part of this normalization, it changes the output of nodetool info to use the correct SI prefixes. The only dependency on this I could locate for CCM is in its parsing of the nodetool info output. This parsing happens in a function without the C* version available, so we can't do a version check to determine correct units. This PR proposes the easy route of supporting both unit types; another option is to refactor the tests/call sites to pass in a C* version, so that we can decide based on version.
(Please note that I'm reviewer for the above ticket, not assignee. PRing this since it is a new contributor and managing a C* ticket/CCM PR/dtest PR …
=> Fixed memory label to align to CASSANDRA-9692 

ccmlib/cmds/node_cmds.py, ccmlib/node.py
`ccm json` is currently broken for Cassandra 3.x, but we can just use the `sstabledump` tool in this case.
=> Use sstabledump for json command if available

ccmlib/common.py
Python3 compatibility problem. this dict will never be large
enough that we need the iterator in py2
Closes #492 
@mambocab and @tolbertam to review, please. (It was Andy/My code that caused the bug)
=> Use dict.items instead of iteritems

ccmlib/dse_node.py
DSE changed the name of the gremlin config file, this allows graph to launch again.
=> sync up gremlin configuration file name with current master

ccmlib/cluster.py, ccmlib/cluster_factory.py
So we can specify that a node's broadcast_address can be used in the seed list. See CASSANDRA-10134 (specifically https://issues.apache.org/jira/browse/CASSANDRA-10134?focusedCommentId=15243094&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15243094)
=> Enable seed addresses to be explicitly set

ccmlib/node.py
Looks like **ccm** is connecting to the **thrift** port by default instead of the binary port **9042**.
````
$ ccm node1 bulkload /tmp/dataset1/keyspace1/standard1/ -v
All host(s) tried for query failed (tried: /127.0.0.1:9160 (com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1] Cannot connect))
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9160 (com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1] Cannot connect))
at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:231)
at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:77)
at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1414)
at …
```
=> Use correct port for sstableloader

ccmlib/cluster.py, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/node.py
@mambocab, please review this as well.
Connected with https://github.com/riptano/cassandra-dtest/pull/1002
Cassci test: http://cassci.datastax.com/view/Dev/view/smccarthy788/job/smccarthy788-cassandra-3.0-dtest/lastCompletedBuild/
=> separated batch_commitlog from set_configuration_options

ccmlib/node.py
Before, this was running a separate process for each sstable. This changes the return, but also allows us to run only a single process.
=> Update sstablemetadata to pass in all sstables at once

ccmlib/node.py
The Node._get_directories() function already prepends the node root path
returned by get_path(). Therefore, fix up the mkdir() call not to
prepend the same directory again.
Fixes the following error in when running the test snippet from README:
$ ./test.py
Traceback (most recent call last):
File "./test.py", line 11, in <module>
cluster.populate(3).start()
File "/home/penberg/ccm/ccmlib/cluster.py", line 223, in populate
binary_interface=binary)
File "/home/penberg/ccm/ccmlib/cluster.py", line 229, in create_node
return Node(name, self, auto_bootstrap, thrift_interface, storage_interface, jmx_port, remote_debug_port, initial_token, save, binary_interface, byteman_port)
File "/home/penberg/ccm/ccmlib/node.py", line 110, in __init__
self.import_config_files()
File …
=> Fix mkdir() call in Node._update_config()

README.md
The Cluster class is now in 'ccmlib.cluster' so fix up the example
snippet in README accordingly.
=> Fix ccmlib example in README

ccmlib/cluster.py, ccmlib/node.py
As a start, this will be useful for specifying `CASSANDRA_LIBJEMALLOC` in
order to speed up dtests
=> Support specifying environment variables

ccmlib/node.py
This is not a proper fix -- these kinds of bugs will keep happening until we do something with the `get_cassandra_version` API. But, fixing that in the general case can be a discussion for another day.
I've run this locally, and it makes CCM successfully create `cdc_raw` on trunk, where the version is `'3.10'.
=> minimal fix for cdc version checking

ccmlib/cluster.py
the main gist here, is now hand back a full-fledged thread to the caller who can .join() the thread when they are done watching logs (typically after cluster stop, but before file cleanup).
=> make log watching more amenable to resource cleanup

ccmlib/dse_node.py
Variable `pidfile` is defined, when the DS agent directory is evaluated.
However, if the agent is not installed, `pidfile` is not defined, which leads to an error.
Unsure though, whether it's an error that the agent was not installed (used DSE 5 + OpsC 6).
=> Fix issue when DSE nodes are removed/cleaned and ds agent is not installed

ccmlib/node.py
I've run this against the code from [this pr](https://github.com/riptano/cassandra-dtest/pull/1086), and it seems to work.
=> use clock for timeout, not a counter

ccmlib/cmds/cluster_cmds.py
When we add a node on the command line, if we duplicate the name of an existing node, it blows away state on disk in the node constructor but then fails to add the node to the cluster when the cluster validates the name.
There isn't a clear way I can see to disentangle this sequence without reworking the whole cluster/node abstraction. For now, we can duplicate the name check so that fat fingering a node name doesn't mess things up too badly.
=> Validate node name on cmdline node add so that we don't mess up the state on node initialization

ccmlib/repository.py
I don't know if a `print_` is the best replacement for raising an error here, but the current implementation isn't good on Python < 3 -- we never see why an error was raised in the first place.
=> Improve repository failure error

ccmlib/common.py
Allow control of the `SPARK_WORKER` resources and a specific 5.0 and above change for the introduction of HADOOP 2 support.
=> Updated DSE environment setting for 5.0 and above

ccmlib/cmds/node_cmds.py
This removes all `nodetool` logic. It wasn't necessary in the first place and makes the command fragile.
=> remove nodetool call from versionfrombuild cmd

ccmlib/common.py
@ptnapoleon, @knifewine: I think this should address the issue raised in https://github.com/riptano/cassandra-dtest/pull/1311#issuecomment-246747914
We should be able to get the default pattern if it is falsy, but exists.
=> allow for an empty string to be represented as the default pattern

ccmlib/cmds/node_cmds.py
@ptnapoleon, I found a little bug. Trying to run `ccm node1 cli` would result in an argument error, since the `run_cli` method doesn't take the `verbose` argument anymore.
I'm happy to bikeshed over how this output is printed.
=> allow for verbose cli. pep8 clean

ccmlib/repository.py, setup.py
This proposes to remove the old form of local:somebranch (requiring LOCAL_GIT_REPO defined in env) and replacing it with a form of local:/some/path/:branch_name . This is to support more easily working with multiple local versions across the filesystem (in multiple git repos). The old way made it clumsy to do that.
I tested this by hand locally and it appears to function well from the command line. If there's any specific cases you can think of I'm happy to test more.
I think the changes here have a low risk outside of local: usage.
=> make local slugs better

ccmlib/node.py
@mambocab or @smccarthy788  to review.
It's a breaking API change, but we use it literally nowhere. Also neither do the python driver tests. And anyone trying to use it would have noticed it does nothing.
=> Actually clear data when node.clear(only_data) is called

ccmlib/cmds/node_cmds.py, ccmlib/node.py
@ptnapoleon, @mambocab: for your consideration.
After we merge [dtest 1320](https://github.com/riptano/cassandra-dtest/pull/1320), we will no longer use output files anywhere in dtest. We have the option to remove them from ccm.
Thoughts?
=> remove use of output files

ccmlib/cluster.py
Leaving node as false for now, since sometimes when we
start nodes, in dtest, we're doing so to expect them to fail.
But clusters should generally always work on startup. The case
where one wants an entire cluster to fail to start is an odd one
@mambocab to review
CI is generally good, so I just need a few changes to dtest for this to work
=> Default to starting clusters with binary_proto=True

ccmlib/repository.py
@mambocab & @ptnapoleon: please review.
Just a little tweak. I'm trying to allow users to define aliases of git urls in a configuration file. Seems easier than `-v git:smccarthy788/cassandra-fork` every time.
Config files should look like
```
alias_name = some.git.url
```
be located at `.ccm/config`, and can be used as `ccm create -v alias:alias_name ...`
=> allow for user configured aliases

ccmlib/repository.py
ConfigParser is not a valid module in py3. It's py3 contemporary is configparser. I've added a conditional import to work around the issue.
=> Conditional import for py3

ccmlib/cluster.py, ccmlib/node.py
This is to support https://issues.apache.org/jira/browse/CASSANDRA-11115, and work at least as far as cassandra-dtests are involved on 4.0. Hopefully this doesn't break anything for earlier versions.
=> Don't include removed thrift options when running against C* 4.0

ccmlib/node.py
Quite often, it takes 15 or 20 seconds for the CQL binary protocol to start listening when starting a node. I thought about adding a `--protocol-wait-timeout` option but I think the added value is very limited. Simply increasing the timeout to 30 seconds will probably handle most cases.
=> Increase waiting time for protocols to 30 seconds

ccmlib/cmds/node_cmds.py, ccmlib/node.py
[CASSANDRA-12510](https://issues.apache.org/jira/browse/CASSANDRA-12510) introduces behavior that prevents a successful
decommission unless the number of remaining replicas meet the
replication factors of all keyspaces.  A new --force option was added to
bypass this behavior.  Added this option to the 'ccm decommission'
command.
=> Add --force option to decommission for CASSANDRA-12510.

ccmlib/dse_node.py
Starting with DSE 5.1, these ports are set automatically
=> For DSE installs, only set Spark shuffle port for 5.0.x versions

ccmlib/common.py
... of running operations in parallel. 
They would end up creating same conf anyways, right?
=> Use PID as part of tmp file name to avoid race conditions 

ccmlib/dse_node.py
dsetool previously always targeted localhost.  Since dsetool is a
node-specific command, it makes sense to use the ip address of the node.
In addition, also passes in the binary port to use in the event that it
is different than the default port (9042).
=> Update dsetool to use node address and port

ccmlib/repository.py
Looks like status is a string looking like
`b'## cassandra-3.0...origin/cassandra'` 
which causes re.search to fail in python3 in an error that looks like 
`can't use a string pattern on a bytes-like object`
=> Fixed python3 compatibility issue

ccmlib/cmds/node_cmds.py, ccmlib/node.py
This adds an additional parameter to the `run_sstabledump` method to allow the command to print it's results immediately rather than returning them in an array.
This changes lets `ccm node1 -k ks -c tb` work correctly on a >3.0 node while maintaining compatibility with the dtests that also use `run_sstabledump`
=> Allow sstabledump to print results from command

ccmlib/common.py
Hi,
Sometimes the socket is left opened here. I'm seeing a bunch of these logs in python3 every time the function is called:
`ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 43928)>`
=> Closed open socket in check_socket_listening

ccmlib/dse_cluster.py, ccmlib/repository.py
This PR corrects Opscenter download location to `enterprise` instead of `community` and uses download credentials.
=> Fix opscenter download

ccmlib/cluster.py
Hello, 
I noticed that when I create a cluster like so: 
ccm create test --datadirs=3 
After I populate the cluster with nodes, the nodes still come up with only 1 data directory (data0). Digging into it it looks like cluster.conf only has datadirs: 1, and that seems to be because when we first create the cluster after we set the number of datadirs we do not update cluster.conf. (See cluster_cmds.py:ClusterCreateCmd.run).
I believe this fixes it, feel free to let me know if there is any feedback. 
Thanks!
=> Update config after setting datadirs so that it persists when populating nodes

ccmlib/repository.py
this adds support for using maven mirrors for all c* builds:
```
→ cat ~/.ccm/build.properties.default
artifact.remoteRepository.central:     <my maven mirror>
artifact.remoteRepository.apache:      <my maven mirror>
```
manual test:
```
10:53:57,205 repository INFO --- Cassandra Build -------------------
10:53:57,205 repository INFO Copying /home/chris/.ccm/build.properties.default to /home/chris/.ccm/repository/githubCOLONapacheSLASHtrunk/build.properties
...
BUILD SUCCESSFUL
Total time: 59 seconds
10:54:56,756 repository INFO 
10:54:56,756 repository INFO 
--- cassandra/stress build ------------
Current cluster is now: test1
```
=> support custom build.properties

ccmlib/repository.py
for some reason 2.2.3 is missing from http://archive.apache.org/dist/cassandra/2.2.3/ currently.
when doing `ccm create test1 -v 2.2.3 -n 1` we get this error:
```
10:12:17,709 ccm WARNING Downloading 2.2.3 failed, due to not all arguments converted during string formatting. Trying to build from git instead.
```
after this PR:
```
→ ccm create test1 -v 2.2.3 -n 1
13:32:52,99 ccm WARNING Downloading 2.2.3 failed, trying to build from git instead.
The error was: Invalid version 2.2.3 (underlying error is: HTTP Error 404: Not Found)
```
i added the `The error was:` at the end so that we do not inline the exception message like that.
this PR also fixes this minor formatting issue:
```
Building C* version git:cassandra-2.2.3 failed. Attempted to delete …
```
=> fix string format bugs

ccmlib/node.py, tests/test_lib.py
follow up to #591
we make sure that `Exception` (capital E) is found as well
=> treat any Exception in WARN log as error

ccmlib/dse_node.py
This adds the handling added in #510 to DSE methods.
It's not clear to me how the C\* counterparts in `node.py` are tested. What should I do to test these changes? They work locally for me.
This is a breaking API change.
=> handle failure in dse shell-out methods

ccmlib/cluster.py, ccmlib/cmds/cluster_cmds.py
it was not possible to give a custom nodes parameter to stress, because all live nodes are added all the time.
before:
```
→ ccm status test1                                           
Cluster: 'test1'
----------------
node1: UP
node3: UP
node2: UP
→ ccm stress write n=1000 -node whitelist 127.0.0.1,127.0.0.2
-node is defined multiple times. Each option/command can be specified at most once.
Usage:      cassandra-stress <command> [options]
Help usage: cassandra-stress help <command>
...
```
after this PR it is possible:
```
→ ccm status test1                                           
Cluster: 'test1'
----------------
node1: UP
node3: UP
node2: UP
→ ccm stress write n=1000 -node whitelist 127.0.0.1,127.0.0.2
******************** Stress Settings ********************
...
Node:
Nodes: …
```
=> allow using nodes option for stress

ccmlib/dse_node.py
Starting with DSE 5.0.10/5.1.3 these are not automatically created by the DSE
startup scripts, but must be created by the user or the standalone or package
installer.
Tested on current dev branches for DSE 4.8.x, 5.0.x, 5.1.x and master.
=> Automatically create Spark working directories

ccmlib/dse_node.py
Commit `f9c70c0` introduced an indentation error whereby the variable
pidfile was referenced without being defined. This solves issue #565, where
`ccm stop` fails upon calling `_stop_agent()`.
=> Fix indentation in _stop_agent

NETWORK_ALIASES.md, README.md
Setting up permanent network aliases on Mac OSX is painful and a lot of examples on the web work only for older OSX versions. This PR includes detailed steps tested on OSX Sierra 10.12.6.
In the first commit I moved all the OSX-specific instructions to the new NETWORK_ALIASES.md, but then I realized the original instructions for temporary aliases were still useful in README.md as a quick-start guide to get new users running quickly.
=> Detailed instructions for creating permanent network aliases on Mac OSX.

ccmlib/dse_node.py
This is failing to start after deleting `/var/lib/dsefs`, 
```
ccm create 5.1.2 -v 5.1.2 -n 3
ccm setworkload spark
ccm start
```
Looks like when starting spark the working dirs for dsefs are set to the default directory.
=> Set dsefs options if spark is a workload

ccmlib/cmds/command.py
Only allow `[a-zA-Z0-9_-]+` in the cluster name.
Please see  https://github.com/pcmanus/ccm/issues/421.
=> Prohibit non-word characters as clustername

ccmlib/node.py
I am working on a new test in cassandra-dtest where I need to submit a byteman rule to a single node,  after restarting it. Might not be the best way, so I am open to suggestions.
=> Support byteman startup scripts when calling start()

ccmlib/dse_node.py, ccmlib/node.py
In dse_node there are some cases where the thrift network_interface is
used to derive the ip address.  It is not guaranteed that thrift will be
enabled/present.  In this case, create an ip_addr member that is set
based on thrift or binary interface ip address.
=> Derive ip address based on thrift or binary interface

ccm, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/command.py, ccmlib/cmds/node_cmds.py, ccmlib/common.py
While looking into #258 (use of `argparse` instead of `optparse`\*), I noticed that:
- some of the `Cmd` subclasses had separate fields for `usage` and `descr_text`, but others didn't. So I refactored all `Cmd` subclasses to have them. 
- having the subcommand options in an iterable form would be very convenient for use with `argparse`'s subcommand support. Hence, I pulled out the options to a new `options` field in these classes. 
This left much of the `get_parser()` and `description()` methods repetitive. By moving `ignore_unknown_options` to a field as well, I could eliminate *all* definitions of `get_parser` and `description` in favour of methods in the parent `Cmd` class.
By renaming the `cluster_cmds()` and `node_cmds()` functions, I could also do some DRY refactoring in the main …
=> Refactor Cmd subclasses and ccm

ccmlib/dse_node.py
before:
```
ccm create test --install-dir=/Users/xianteng/bdp/
ccm populate -n 1
ccm setworkload graph
Traceback (most recent call last):
File "/Users/xianteng/ctool-env/bin/ccm", line 90, in <module>
cmd.run()
File "/Users/xianteng/ctool-env/lib/python2.7/site-packages/ccmlib/cmds/cluster_cmds.py", line 855, in run
node.set_workloads(workloads=self.workloads)
File "/Users/xianteng/ctool-env/lib/python2.7/site-packages/ccmlib/dse_node.py", line 71, in set_workloads
graph_options['gremlin_server']['host'] = self.ip_addr
TypeError: 'NoneType' object does not support item assignment
```
after, things work fine
it doesn't look like there was ever a `graph.gremlin_server.host` in dse.yaml
=> removed nonexistent yaml key

.travis.yml, README.md, ccm, ccmlib/cmds/command.py, ccmlib/remote.py, misc/Vagrantfile
* Handles `--dse-credentials`, `--node-ssl`, and `-ssl`
* Files will be copied from local to remote before execution
* Updated documentation to reflect new remote options
This update adds the ability to specify a remote host to execute CCM
commands on. The remote machine must be pre-configured to accept SSH
connections, sequential IP addresses for simple node creation, and a
installed instance of CCM; see misc/Vagrantfile for simplified guest
installation.
__Note__: This update is optional and requires that `paramiko` is
installed in order to function.
=> Add the ability to remotely execute CCM commands

ccmlib/common.py, ccmlib/dse_node.py
Newer versions of DSE allow configuring spark resource settings via dse.yaml in the following manner:
```yaml
resource_manager_options:
worker_options:
memory_total: 0.1
cores_total: 0.2
```
This sets the resources used by spark as a ratio of system resources instead of fixed.  I chose 0.1 memory and 0.2 cores to get close to the previous config (1024M / 2 cores) on a modern mac book pro (1.6GB ram, 2 cores).  The environment variables `SPARK_WORKER_MEMORY` and `SPARK_WORKER_CORES` are still used for older versions.
=> Use dse.yaml resource_manager_options in newer DSE versions for spark

ccmlib/common.py
Currently, all `common` module log method's outputs are piped to stderr, regardless of level. Logging `common.info` and `common.debug` method call output to stdout instead might make more sense.
You can see the result of this behavior by creating a new cluster that requires the specified version to be downloaded. The `Downloading %url` message will be piped to stderr instead of stdout:
```bash
ccm create -v 3.9 test 1> stdout.log 2> stderr.log
```
=> Pipe info- and debug-level events to stdout instead of stderr

ccmlib/cluster.py, ccmlib/cluster_factory.py, ccmlib/common.py, ccmlib/dse_cluster.py, ccmlib/dse_node.py, ccmlib/node.py
Noticed that common.get_version_from_build and
get_dse_cassandra_version were invoked frequently when creating clusters
and using ccm command later (as many as 35 times).
These functions parse files on the file system to extract C* and DSE
versions.  Updated code to now store version and cassandra_version
with cluster and node config.
Also updated get_dse_cassandra_version to use `bin/dse cassandra -v`
instead of looking for cassandra-all.jar and parsing version number from
it.
=> Store cassandra_version with config to prevent repeated parsing

ccmlib/cluster.py, ccmlib/cluster_factory.py, ccmlib/dse_cluster.py, ccmlib/dse_node.py, ccmlib/node.py
* Replaced cassandra_version overload with 'derived_cassandra_version'
to avoid breaking backwards compatibility.
* Remove 'version' from config, if persisted it is reused and causes
attempt to download version instead of using local directory.
=> Fix issues with stored version config.

ccmlib/common.py
output is of type bytes, it's producing in that line an exception with `cannot use a string pattern on a bytes-like object` in python3
=> Fix py3 compatibility re.search

ccmlib/cluster.py
if running 4.0 or higher and using ssl, set new `server_encryption_options. enabled` to true in yaml.
Note: committing this is required for CASSANDRA-10404
=> Add support for new CASSANDRA-10404 yaml property

ccmlib/node.py
Is there any reason not to update the version value when changing the install directory for a node ([just as we do for cluster](https://github.com/pcmanus/ccm/blob/master/ccmlib/cluster.py#L96))? Otherwise this seems to cause issues for upgrade tests by sharing hints directories as described in 10f3ea95dee352a106bcb20182ec31354c490fc0.
=> Update node version on install_dir change

ccmlib/repository.py
Currently all tests on builds.apache.org seem to be broken in case they are trying to clone from github using ssh. 
Example:
https://builds.apache.org/view/A-D/view/Cassandra/job/Cassandra-3.0-dtest/lastCompletedBuild/testReport/batch_test/TestBatch/logged_batch_compatibility_2_test/
Starting with [72b181a2a](https://github.com/apache/cassandra-dtest/commit/72b181a2ad8c597396ec76c654ddb8b635c102dc) we now clone using ssh instead of http, which requires the server's ssh key in `known_hosts`. As this doesn't have to be the case on CI nodes, I'd suggest to stick with http instead, as the apache repo on github is read-only anyways.
=> Use http for cloning apache repo from github

ccmlib/common.py, ccmlib/node.py, tests/test_common.py
Fixes parsing of the version number (if the version number is just `9` or `10` for the `.0.0` releases).
Updates to GC-logging config for Java 9 and newer (applies to Java9 branch)
=> Java 9 additions

ccmlib/dse_node.py, ccmlib/node.py
When running the commands:
`ccm updatedseconf "authorization_options.enabled: true" # dse.yaml is updated as expected` 
`ccm updateconf "authorizer: com.Authorizer"`
The last commands updates cassandra.yaml and restores dse.yaml to the default removing the effect of the first command.
This is because on `updateconf` the following stack happens
```
ClusterUpdateconfCmd.run ->
self.cluster.set_configuration_options -> 
self._persist_config ->
node.import_config_files ->
self.copy_config_files # This overrides all the configuration files, which for a DseNode include dse.yaml and cassandra.yaml
self._update_yaml # This is a private method so the _update_yaml from Node is called instead of the method from DseNode, therefore only the cassandra.yaml is updated leaving us with the overriden …
```
=> rename __update_yaml -> _update_yaml so DseNode calls it's own method

ccmlib/cmds/node_cmds.py, ccmlib/node.py
When `ccm node start --verbose` fails, the stderr output is lost; in addition, `None` is printed:
```
ccm node1 start --verbose
None
Error starting node node1
Standard error output is:
```
With this patch, we see:
```
ccm node1 start --verbose
Error starting node node1
Standard error output is:
intx ThreadPriorityPolicy=42 is outside the allowed range [ 0 ... 1 ]
Improperly specified VM option 'ThreadPriorityPolicy=42'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
(which showed my problem to be an installed JDK 9 in the path combined with no set JAVA_HOME)
=> Remove "None" from output and show stderr on failed start

ccmlib/node.py
Dtests interacting with external cassandra tools currently fail in Python3 environments, as the output is not decoded before passed to `JSON.loads()`.
Example:
https://builds.apache.org/view/A-D/view/Cassandra/job/Cassandra-devbranch-dtest/494/testReport/offline_tools_test/TestOfflineTools/test_sstabledump/
=> Decode output of external tool subprocess

ccmlib/node.py
Byte values for err channel should be decoded as well, see 0a5824508
cc @aweisberg
=> Decode also err output of external tool subprocess

ccmlib/node.py
Addresses Issue #670 to decode empty bytes objects (b'') for stdout and stderr piped from subprocess. Without this change, handle_external_tool_process returns inconsistently typed results - it returns stdout and stderr as strings if they're non-empty, but as bytes if they're empty.
=> Issue #670: also decode empty stdout and stderr to strings

ccmlib/common.py
Fix https://github.com/riptano/ccm/issues/609
=> Fix to exit when java version check is failed with OSError

ccmlib/cluster.py, ccmlib/cluster_factory.py, ccmlib/cmds/cluster_cmds.py, ccmlib/common.py, ccmlib/dse_cluster.py, ccmlib/dse_node.py, ccmlib/node.py
@kishkaru 
Command enables this on all nodes in the cluster. `ccm remove` behavior is altered slightly, to always stop gracefully if aoss is enabled, otherwise we'll leak spark processes. No DC specific enablement, or disablement of aoss are in this PR. Let me know if you need those.
=> Add command to enable DSE's AOSS

ccmlib/repository.py
This adds the capability to override the repository locations for downloading cassandra, DSE, and OpsCenter.   This is useful for situations such as when CCM is used as part of a continuous integration workflow where a local mirror is set up so downloads can be done quickly over the local network.
Repositories can be configured via the `[repositories]` section of the `~/.ccm/config` file which was already defined for git aliases.  For example:
```
[repositories]
cassandra = http://mirror.awesomeco.intranet/apache/cassandra
dse = http://mirror.awesomeco.intranet/tar/dse/dse-%s-bin.tar.gz
opscenter = http://mirror.awesomeco.intranet/tar/opscenter/opscenter-%s.tar.gz
```
=> Add ability to configure archive repository locations via ~/.ccm/config

ccmlib/dse_cluster.py, ccmlib/repository.py
ConfigParser supports string interpolation which I never intended
to be supported and causes issues with Python 3.x when specifying
a dse mirror repository, which expects a format like:
[repositories]
dse = http://myrepo/enterprise/dse-%s-bin.tar.gz
Unfortunately, ConfigParser interpolation is not compatible between
2.x and 3.x as 3.x requires escaping '%', where 2.x does not unescape
'%', so using RawConfigParser seems like the best viable solution.
=> Use RawConfigParser instead of ConfigParser

ccmlib/common.py, ccmlib/node.py
CASSANDRA-9608 splits the `jvm.options` file into multiple files. The patch makes ccm check all those files.
=> CASSANDRA-9608 upgrade all jvm.options files

ccmlib/common.py
Some versions of DSE may information log messages to stderr when using
the 'dse' command.  Suppress stderr when parsing version and include
it in error message if we cannot parse the version.
Have already tested and discussed this, so will merge on travis pass.
=> Ignore stderr in bin/dse cassandra -v output

ccmlib/cluster.py, ccmlib/cmds/cluster_cmds.py
#372 Requested adding ccm option that shows nodes' information in a parallel manner.
We implemented that feature "showlogs". By default it shows every node's log by "multitail" command.
By exporting command and options to CCM_MULTITAIL_CMD, you can execute any command and options to view the logs. If you want to specify nodes to be shown in a cluster, execute like
$ ccm showlogs [node1, node2, ...]
=> Solution for #372 , Add "showlogs" command and CCM_MULTITAIL_CMD environment

ccm
Solution for Issue[340](https://github.com/riptano/ccm/issues/340).
If there is CASSANDRA_HOME environment variable, it will be warned.
=> Add warning when CASSANDRA_HOME is set in environment

ccmlib/cluster.py, ccmlib/common.py, ccmlib/node.py, ccmlib/repository.py
Improve removal of configuration options by making it possible to specify a list of options to remove.
Automatically remove unsupported config options on version change.
Include stdout/stderr in exception message for failed compile since this is all CircleCI shows.
=> Improvements for re-enabling upgrade tests for CASSANDRA-14421

ccmlib/cluster.py, ccmlib/common.py, ccmlib/node.py, ccmlib/repository.py
When setting a new version use LooseVersion for the version field in Cluster to be consistent. Some test code fails because it expects a LooseVersion all the time.
When going from > 4.0 version to a < 4.0 version remove the 4.0 options automatically.
=> More fixes for CASSANDRA-14421 to make changing versions easier

.travis.yml, ccmlib/node.py, setup.py
Recently something seems to have changed in circleci, making it leave defunct/zombie processes with symptoms like this: https://circleci.com/gh/krummas/cassandra/1478#tests/containers/25
And ccm currently doesn't handle this scenario - it keeps trying to kill the process but it wont die, this PR adds a check if the process is zombie and then just ignores it.
=> handle zombie processes

ccmlib/node.py, ccmlib/repository.py
=> allowing dash in Cassandra version number, i.e. 4.0.alpha2

.travis.yml, tests/test_lib.py
Currently travis runs with JDK11 and tests that bring up nodes don't
work because of
```
[node1 ERROR] b"intx ThreadPriorityPolicy=42 is outside the allowed range [ 0 ... 1 ]\nImproperly specified VM option 'ThreadPriorityPolicy=42'\nError: Could not create the Java Virtual Machine.\nError: A fatal exception has occurred. Program will exit."
```
Another issue is that the build doesn't work with Python 3.4.
It makes sense here to test with latest C* 4.0 and with Python 3.8.
=> Fix Travis Build

ccmlib/node.py, setup.py
I am running into an issue that ccmlib assumes [all input will be terminated by a `;`](https://github.com/riptano/ccm/blob/275699f79d102b5039b79cc17fa6305dccf18412/ccmlib/node.py#L910). This isn't true in case of lets say comments or multi-line comments. ccmlib should optionally take a terminator to avoid this issue.
Here's an example of a failure:
```python
self.node1.run_cqlsh(
"""/* multiline
*
* comment */
""")
```
Attached patch fixes the issue. @snazy @nastra could you please review this PR?
=> ccmlib should not always terminate cql statements with a ';'

ccmlib/cluster.py, ccmlib/common.py, ccmlib/node.py, ccmlib/repository.py, tests/test_lib.py
Also:
* Add a new "version source type" `clone:/path/to/local/cassandra/clone` to re-enable upgrade-dtests for dev-CI and local upgrade-dtest runs after CASSANDRA-14420 + CASSANDRA-14421
* Introduce new node startup logfiles for stdout+stderr
* Use `./gradlew` instead of `ant` to build C*, if `gradlew` is present
=> CASSANDRA-15835: Use the right Java version + JAVA_HOME when building C* from source / master

ccmlib/cluster.py, ccmlib/common.py, ccmlib/node.py, ccmlib/repository.py, tests/test_lib.py
Also:
* Add a new "version source type" `clone:/path/to/local/cassandra/clone` to re-enable upgrade-dtests for dev-CI and local upgrade-dtest runs after CASSANDRA-14420 + CASSANDRA-14421
* Introduce new node startup logfiles for stdout+stderr
* Use `./gradlew` instead of `ant` to build C*, if `gradlew` is present
=> CASSANDRA-15835: Use the right Java version + JAVA_HOME when building C* from source / cassandra-test

ccmlib/dse_node.py
@snazy DSE needs this to match the signature of the node.start method.
=> Add jvm_version to dse_node.start()

ccmlib/node.py, tests/test_lib.py
Before: wait up to 600s for "Starting" msg in logs, then configured timeout for port open
After: wait up to timeout for "Starting" msg in logs then up to timeout for port open
It also brings back the ability to provide timeout in seconds instead of boolean for the `Node::start()` method.
Validation:
https://ci-cassandra.apache.org/blue/organizations/jenkins/Cassandra-devbranch/detail/Cassandra-devbranch/307/pipeline
https://ci-cassandra.apache.org/job/Cassandra-devbranch-dtest-upgrade/13/
And with fixes to extend timeouts for bootstrap or node replacement tests:
https://ci-cassandra.apache.org/blue/organizations/jenkins/Cassandra-devbranch/detail/Cassandra-devbranch/308/pipeline :ok:
https://ci-cassandra.apache.org/job/Cassandra-devbranch-dtest-upgrade/14/ :ok:
=> Use NODE_WAIT_TIMEOUT for log watch

ccmlib/repository.py
I get failures when trying to use github forks as cassandra version due to some git shenanigans.
Works flawlessly with https though so it would be good to move to it as a default I guess.
=> Use https for cloning github Cassandra repos

ccmlib/node.py, tests/ccmtest.py
prior to this change, a node's environment variables set during cluster creation would be overridden and persisted in node config when start is called
=> update (instead of replace) node environment variables when starting

misc/ccm-macos.bash
The ccm-macos.bash script allows the creation of a CCM cluster. It supports the `NUM_NODES`
parameter to determine the number of nodes to configure in the cluster. Additionally, it will
configure the required interfaces required for the cluster to start up. It requires `sudo` for
the operation, so this script will need elevated privileges to configure the interfaces
required.
Additionally, this script relies on a configured virtualenv. Conveniently, it can leverage
Cassandra's pylib virtualenv. If the virtualenv is not loaded, it will check whether
Cassandra's pylib virtualenv has been already initialized. If so, then it will activate the
virtualenv. Otherwise, it will initialize the virtualenv and install the requirements.
The name of the cluster defaults to `test`, but it can be …
=> Helper script to provision a CCM cluster in MacOS

README.md, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/common.py, ccmlib/dse_cluster.py, ccmlib/node.py, tests/test_lib.py
Problem: for Cassandra 5 not built from the sources, Java version is not selected properly - it is assumed it works with either current version or Java 8.
Fixes:
- For Cassandra 5.1+ binary distribution, the supported versions are retrieved from cassandra.in.sh
- If supported Cassandra version cannot be retrieved from either build.xml (source dist) or cassandra.in.sh (bin dist), use the hardcoded version - the conditions cover all supported Cassandra versions starting from 2.2.
- Refactored Java selection logic - clearly distinguish supported Java versions by Cassandra and available Java versions in the environment (distributions configured via JAVA_HOME and JAVAn_HOME env variables); prioritizes the supported Java version over the current Java version configured via PATH (which is …
=> Fix Java version selection

README.md, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/common.py, ccmlib/dse_cluster.py, ccmlib/node.py, tests/test_lib.py
The logic works as follows:
1. Look for available Java versions in the env - figure out versions of Java located at `JAVA_HOME` and all `JAVAx_HOME` env vars (actually execute `java -version` to check)
2. Figure out supported Java versions by Cassandra distribution - for Cassandra 5.1+ binary distribution the supported Java versions can be read from `cassandra.in.sh` and for Cassandra 5.0+ source distribution the supported Java versions can be read from `build.xml`. For other Cassandra versions, the supported Java versions are hardcoded in CCM
3. If Java version is explicitly provided - use it if it is available (see 1), warn if it is not supported by Cassandra
4. If `JAVA_HOME` is defined, use that Java distribution if it is supported by Cassandra distribution; if it is not supported, …
=> Cassandra 19636

ccmlib/common.py, ccmlib/node.py, ccmlib/repository.py
1. Before/after starting a node, only JAVA_HOME was stored/restored which could be responsible for divergences between Java version on PATH and JAVA_HOME
2. Method which calls 'java' from the PATH to check its version didn't take into account the updated env
=> Fix confused env usages

ccmlib/repository.py
mirror with refs explicit isn't supported in newer git version.  bare is want is desired, that is don't get upstream remotes.
patch by Mick Semb Wever; reviewed by Brandon Williams
=> Use git clone bare instead of mirror

ccmlib/cluster.py, ccmlib/node.py
CASSANDA-19488 deprecates IEndpointSnitch and replaces it with InitialLocationProvider and NodeProximity classes. In Cassandra, the default yaml config retains the endpoint_snitch setting, whereas the alternative cassandra_latest yaml specifies the new options. CCM injects PropertyFileSnitch into config for multi datacenter clusters, but this is problematic as the old and new config options are mutually exclusive.
This patch injects both the old and new settings into config when the cluster is populated, then removes whichever one was not present in the original yaml once it has been loaded. This allows dtests to run with both the legacy and latest configs and exercises both code paths.
=> Update snitch/location config selection
