riptano/ccm

ccmlib/node.py
I use sstablemetadata and sstablerepairedset in a dtests and have added methods to ccm to support this.
=> Additional methods into node.py to utilize further tools

ccmlib/node.py
sstablesplit command extra kwargs...
=> sstablesplit command extra kwargs

ccmlib/node.py
As part of CASSANDRA-8996, this fixes some spurious test failures on trunk.  When ``_update_pid()`` was called from ``cluster.start()``, there was no wait for the pidfile to exist.   Additionally, there was a timeout of 15s before, and trunk was taking about 17s to write the pidfile.  I've increased the wait to 30s to give it some breathing room.
=> Always wait for the pidfile to exist, increase wait

ccmlib/node.py
Currently, the exit status of nodetool commands is being ignored, which
makes it easy to miss failing nodetool operations.
=> Check nodetool exit status, error on non-zero

ccmlib/cluster.py, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/node.py
If the submitted patch for https://issues.apache.org/jira/browse/CASSANDRA-5791 is accepted, this patch will add corresponding functionality to ccm.
=> implement verify commands - useful iff cassandra-5791 is accepted

ccmlib/cmds/node_cmds.py, ccmlib/dse_node.py, ccmlib/node.py
This also adds the dse command which allows more control over some of the clients.
=> 275 Added JMX_PORT env var to client commands

ccmlib/node.py, tests/test_lib.py
This is a biggish change, but I think the tests demonstrate it is good.
The problem that spurred this was that DEBUG messages containing the string ERROR would spuriously be treated as errors. I ran a dtest that generated errors, and the grep called on the test teardown successfully made the test fail, so that should still work.
=> fix/refactor/test Node.grep_log_for_errors

ccmlib/common.py
Squashed #295. Also cleaned up the code comments.
=> Squashed version of #295

README.md
=> Readme installation instructions

ccmlib/node.py
=> universal_newlines

ccmlib/cmds/node_cmds.py, ccmlib/node.py
Created a new PR with the changes suggested in the older PR (Getsstables #329)
=> Command to list sstables path in a node

ccmlib/node.py
Added a couple of utilities to node, will update later with some comments as to how they work.
=> modified functions

ccmlib/node.py
=> Revert "modified functions"

ccmlib/cluster.py, ccmlib/node.py
This method is being used in more than one class of cassandra-dtest so I thought it would be useful to bring this up to ccm.
=> Added node.waitforcompactions() method

ccmlib/node.py
Helps fix https://issues.apache.org/jira/browse/CASSANDRA-10051
=> removed platform-dependent dependency shlex from ccmlib/node.py

ccmlib/dse_node.py, ccmlib/node.py
This is causing testing of CASSANDRA-6230 to go haywire:
http://cassci.datastax.com/job/iamaleksey-6230-3.0-dtest/4/testReport/junit/junit/auth_test/TestAuth/login_test/
=> Adds creation of hints directory, introduced in CASSANDRA-6230

ccmlib/dse_node.py, ccmlib/node.py
=> Revert "Adds creation of hints directory, introduced in CASSANDRA-6230"

ccmlib/node.py
* added --debug option
* returning stdout, stderr and rc
=> added debugging stuff to sstablesplit tool (needed to debug #10095)

ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py
Start jconsole and connect to running nodes using ccm.
=> Add jconsole command for cluster and nodes

ccmlib/cli_session.py, ccmlib/cluster.py, ccmlib/cluster_factory.py, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/command.py, ccmlib/cmds/node_cmds.py, ccmlib/common.py, ccmlib/dse_cluster.py, ccmlib/dse_node.py, ccmlib/node.py, ccmlib/repository.py
@mambocab to please review alongside me? Thanks.
=> Use autopep8 to fix style issues

ccmlib/node.py
useful for detecting stress failures on dtests
=> add capture_output option to node.stress

ccmlib/node.py
don't use mutable default default arg
and don't do an in-place update to passed arg either
=> node.stress mutability fixes

ccmlib/repository.py
This adds some Python 3 compatability stuff on top of #389. It also addresses @ptnapoleon's comments on that PR.
@ptnapoleon can you review? and @mikefero I'd welcome your feedback if you want to have a look.
I tested this code on Python 2 and 3 using this script:
https://gist.github.com/mambocab/445012d260e71cfcbca6
=> allow sha like branch names

ccmlib/node.py
dtests need to copy debug logs as well, needs this function in ccm
=> debug logs

ccmlib/node.py
@jorgebay and @josh-mckenzie to review
=> Windows fix

ccmlib/repository.py
=> Default to using binaries, instead of source

ccmlib/cluster.py, ccmlib/node.py
For #391.  Added print of stdout/stderr when --verbose is present on startup commands
=> Debug flag

ccmlib/node.py
This PR implements the set_log_level behavior proposed in Issue #387.
In short, recent changes to Cassandra 2.2.2 and above add a separate debug.log.  These broke CCM set_log_level. The previous fix simply set both log levels to the same level, which nullified much of the benefit of adding a separate debug.log. This fix adds behaviors that still retain a sensible amount of information in debug.log based on the log level set.
I've tested this with a few dtests and run it through autopep8.
=> Add sane set_log_level behavior following CASSANDRA-10241

README.md, ccmlib/repository.py
@mambocab to review.
Not finished testing yet, but what do you think?
=> Retry version download from git in default case

ccmlib/cluster.py, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/node.py
@josh-mckenzie and @mambocab to review.
@jorgebay This is what I opened in place of #408.
=> Add option for quiet start on windows

ccmlib/cmds/cluster_cmds.py
@josh-mckenzie Is this what you had in mind?
=> Check for a bad java.exe that is causing some user issues

ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/command.py, ccmlib/cmds/node_cmds.py, ccmlib/common.py, ccmlib/node.py, ccmlib/repository.py
@mambocab to review and confirm these are all sensible changes
=> Make fixes to silence pyflakes

ccmlib/cluster.py, ccmlib/dse_node.py, ccmlib/node.py
@mambocab to review. #417 brought to my attention that this mistake was occurring in our codebase.
=> Remove all usages of empty lists in kwarg defaults

ccmlib/cluster.py, ccmlib/cluster_factory.py, ccmlib/cmds/cluster_cmds.py, ccmlib/node.py
@krummas Opening a PR, so I can consolidate review here.
Needs merged at the same time as https://github.com/riptano/cassandra-dtest/pull/727
=> multi datadir support

ccmlib/node.py
=> Set gc.log location properly per node

ccmlib/cluster.py, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/common.py, ccmlib/dse_cluster.py, ccmlib/dse_node.py, ccmlib/node.py
@mambocab and @kishkaru to review. I'm running dtest against this right now to make sure I didn't break anything. It might be worthwhile to run a driver CI build against this? If that's something easily do-able.
=> Start fixes

ccmlib/cluster.py
=> Stagger node starts in jdk7

ccmlib/cmds/cluster_cmds.py, ccmlib/common.py
=> Allow passing in literal yaml to updateconf

ccmlib/cmds/cluster_cmds.py
Slight fix needed from this change:
https://github.com/pcmanus/ccm/commit/be70b51a258ab0450522a25621998928dd664e90
=> Fix updatedseconf command

ccmlib/common.py, ccmlib/node.py
@mambocab to review, while I run on CI. This fixes the relevant windows test, which is promising.
=> Only update the envfile in __update_envfile

ccmlib/common.py, ccmlib/node.py
=> Fix python3 string handling mistakes. Closes #467

ccmlib/dse_node.py
Noticed that the environment variables for spark defined in `common.make_dse_env` were not actually being used because `resources/spark/conf/spark-env.sh` was overriding them when it was sourced in.   Fixed this by updating this file with the proper environment variables from any environment variable in `make_dse_env` found in this file.
Without this, files get created in /var/lib/spark and /var/log/spark.
=> Update spark-env.sh with node-specific environment variables.

ccmlib/node.py
Starting with CASSANDRA-10494 the remote debug port setting has moved to `jvm.options`.
=> Enable debug port in jvm.options with 3.2+

ccmlib/cmds/node_cmds.py, ccmlib/node.py
Hi.
I love `ccm node json` command since it iterates all sstables automatically.
So, I'd like to add --key option into json command (and some updates).
Could you please review this PR?
- Add support -key option to specify keys to be included to json command.
- Make filename optional for json command (output to stdout if no
filename is specified).
- Add some useful prints for json command in sstabledump mode.
```
./ccm node1 json -k test -c table1 --key
['/home/yagotou/.ccm/test-3.4/node1/data0/test/table1-35ed6e80fb0111e5adf569e5f575cda5/ma-1-big-Data.db']
-- ma-1-big-Data.db -----
[
{
"partition" : {
"key" : [ "a" ],
"position" : 0
},
"rows" : [
{
"type" : "row",
"position" : 15,
"clustering" : [ "a" ],
"liveness_info" : { "tstamp" : 1459841850412732 },
"cells" : [
{ "name" : "c3", …
```
=> Add -key option/Make filename optional in ccm json

ccmlib/dse_node.py
- update to match current DSEFS config changes
- omit settings which are left as default values
=> Update DSEFS configuration

ccmlib/cluster.py, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/node.py
=> Revert "separated batch_commitlog from set_configuration_options"

ccmlib/cluster.py, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/node.py
=> Revert "Revert "separated batch_commitlog from set_configuration_options""

ccmlib/node.py
@ptnapoleon: Please review
Connected with https://github.com/riptano/cassandra-dtest/pull/1034
=> added methods to find gc & compaction logs

ccmlib/node.py
For [CASSANDRA-8844](https://issues.apache.org/jira/browse/CASSANDRA-8844). Don't merge until that's committed to trunk.
=> add cdc directories to yaml processing

ccmlib/repository.py
@ptnapoleon can you review please?
=> Fix wrong parameters

ccmlib/dse_node.py
These include:
hadoop2_client configuration
correct configuration of the binary folders
setting DSE_HOME in the dse-env.sh (used by a number of CLI tools)
settings for Spark 1.6 integration
=> Changes to DSE node configuration for 5.0

ccmlib/dse_node.py, setup.py
@mike-tr-adamson and @jkni to review
I don't see why this method existed in the first place, it has no dse specific logic? Closes #536
=> Use same nodetool API in dse_node and node

ccmlib/node.py
@mambocab, please review. I multiplexed one of the test failures you pointed out here: https://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/233/
=> Subprocess failure fix

ccmlib/node.py
@ptnapoleon, please review. This was code added to `compaction_test.py` which was requested to be implemented in ccm.
=> add get_sstable_data_files method

ccmlib/cluster.py, ccmlib/common.py
@ptnapoleon & @mambocab, how much of a need do you feel there is for this function?
=> add grep_nodes_for_patterns method

ccmlib/node.py
@ptnapoleon & @mambocab, please review.
There is one thing I'm not sure about, which I had just copied over from `wait_for_binary_interface()`: the conditional based on version number 1.2 in line 508. Is this the correct version?
=> implement wait_for_thrift_interface

ccmlib/cluster.py
@ptnapoleon, this is a review nit from the related dtest PR.
=> specify timeout period is in seconds

.travis.yml, ccmlib/cli_session.py, ccmlib/cluster.py, ccmlib/cluster_factory.py, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/command.py, ccmlib/cmds/node_cmds.py, ccmlib/common.py, ccmlib/dse_cluster.py, ccmlib/dse_node.py, ccmlib/node.py, ccmlib/repository.py
This PR is for checking out Travis CI
=> Add a .travis.yml

ccmlib/common.py, ccmlib/node.py, setup.py
=> Loose versions

ccmlib/cluster.py, ccmlib/cmds/cluster_cmds.py, ccmlib/node.py
@ptnapoleon, for your review. Are you seeing any other errors using `ccm cli` from the command line?
=> make cli args consistent through cluster and node. Closes #553

ccmlib/node.py
DSE workloads can produce a lot of output on start.  In particular, it will print the full command line used.  With DSE, this can exceed 40,000 characters.
Using subprocess.PIPE has limitations, particularly that after 65535
characters, it may block the subprocess (see:
https://thraxil.org/users/anders/posts/2008/03/13/Subprocess-Hanging-PIPE-is-your-enemy/).
Using a temporary file works around this possible occurrence.
Also added a small change to prevent printing stderr multiple times.
=> Use SpooledTemporaryFile for stderr in subprocess.

ccmlib/repository.py
Addendum #556 (commit 5143a76)
=> next can not be called on a TarFile object

ccmlib/cluster.py, ccmlib/dse_cluster.py, ccmlib/dse_node.py, ccmlib/node.py, tests/test_common.py
Uses the merge_configuration function from common.py to merge changes from updateconf and updatedseconf. Also tests merge_configuration function.
=> CCM updatedseconf resets yaml back to defaults

ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/node.py
Allowable Windows signals can be found here: https://msdn.microsoft.com/en-us/library/xdkz3x12.aspx#Anchor_2
=> Correct signal events on Windows

ccmlib/repository.py
@jkni (and @djbowers ) to review please. I'll run some CI to make sure this doesn't break anything.
=> Handle branch divergences in git cache more appropriately

ccmlib/repository.py
I'm not particularly sure who might want to review this, let's try @guyboltonking?
=> Rotate & do not overwrite last.log

ccmlib/dse_node.py
the tools directory is not currently copied over to the ccm nodes so tools commands are not being found for dse nodes
=> Move tools dir to correct location for dse

ccmlib/node.py
@ptnapoleon, for your consideration.
=> grep WARN log lines for exceptions

ccmlib/repository.py
=> Use asf r/o repo to pull C*

ccmlib/common.py
Testing locally before merging. @iamaleksey to review, please
=> Overwrite in.sh on upgrade. Closes #463

ccmlib/cmds/node_cmds.py, ccmlib/dse_node.py, ccmlib/node.py
@mambocab and @bcantoni to review, please
=> Print output from dsetool. Don't capture dse interactive shells.

ccmlib/node.py
followed the implementation of "repair function".
close #546
=> Allow options when calling compact, flush, cleanup API

ccmlib/node.py
We were hanging forever if the jvm fails to start
=> Timeout in node start even when system.log is not written

ccmlib/cluster.py, ccmlib/dse_cluster.py
@ptnapoleon Please review the changes you suggested. Let me know if something does not look good. Thanks for helping out!
=> Fix node startup timeout

ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py
@mambocab does this resolve your issue?
=> Correctly read from process.stderr_file instead of empty process.stderr

.travis.yml, setup.py
=> Update travis yaml to test for Python 3.5.4 and 3.6.3.

ccmlib/dse_node.py, ccmlib/node.py
=> Print helper message when invalid arguments are supplied to tool process

ccmlib/node.py
=> Fix stress python3 compatibility and other consistency issues

ccmlib/dse_node.py, ccmlib/node.py
This PR cherry-picks Ariel's toolerror fixes for the regressions introduced in the last CCM release.
=> Cherry-pick toolerror fixes

ccmlib/node.py
This reverts commit 5c4a2d45a42da15ca33aefd13bdbed9e803931eb.
=> Revert "stdout is returning bytes in python 3 causing this to fail."

README.md
I spotted one more URL to update.
=> Update git-wip URL to gitbox

ccmlib/cluster.py, ccmlib/node.py
Update address patterns for changes to InetAddressAn…dPort.toString
=> Supporting changes for CASSANDRA-15937

ccmlib/cluster.py
This is mostly for Stargate PR https://github.com/stargate/stargate/pull/114
=> Add env. var for default start timeout

ccmlib/cluster.py, ccmlib/node.py
This is intended to enable Stargate CI test with DSE 6.8 persistence: https://github.com/stargate/stargate/pull/182
=> Set metadata dir and add start timeout override

ccmlib/dse_cluster.py
This fix is required by [Stargate](https://github.com/stargate/stargate) CI.
=> Restore the old way of configuring seeds for DSE

README.md
brew link is outdated, updated accordingly. Thanks @thobe for reporting.
=> Update Homebrew link in README.md

.gitignore, README.md, tests/__init__.py, tests/conftest.py
Also update README.md with a bunch of corrected/new info.
=> Fix broken nosetest to pytest fixtures

ccmlib/common.py
Patch by Jacek Lewandowski for CASSANDRA-18678
=> Fix get_supported_jdk_versions

README.md, ccmlib/cluster.py, ccmlib/common.py, ccmlib/node.py, requirements.txt, setup.cfg, setup.py, tests/test_lib.py
This PR rebases the `converged-cassandra` branch on the current `master` to include the latest updates.
=> Rebase converged-cassandra branch on latest master

ccmlib/cluster.py, ccmlib/cluster_factory.py, ccmlib/cmds/cluster_cmds.py, ccmlib/dse_cluster.py, ccmlib/node.py
Rebasing the `converged-cassandra` branch on the latest `master`  for the converged cassandra 5.0 rebase.
=> Rebase converged-cassandra on latest
